# Generated by Django 5.2.1 on 2025-05-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='user_id',
            new_name='user',
        ),
    ]
